[package]
name = "vcf2gt"
version = "0.1.0"
authors = ["b34533"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgzip = "0.0.3"
